version: '3'
services:

  #Postgres Service
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: example
      POSTGRES_DB: development
    ports:
      - "5432:5432"
    volumes:
      - dbdata-postgres:/var/lib/postgresql/data
    networks:
      - app-network

  #NodeJS Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    ports:
      - "8081:8081"
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata-postgres:
    driver: local
